name: fitness_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3  # Updated version
  geolocator: ^13.0.2  # Updated for better compatibility
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^28.1.36  # Updated version
  intl: ^0.19.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated version

flutter:
  uses-material-design: true